spring:
  datasource:
    username: root
    password: hundsun1234
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.36.153:3306/activi1?characterEncoding=utf-8
    initial-size: 5
    max-active: 20
    max-idle: 8
    min-idle: 3
    max-wait: 500
    remove-abandoned: true
    remove-abandoned-timeout: 180
    test-while-idle: true
    ##验证
    validation-query: SELECT 1
    validation-query-timeout: 1
    time-between-eviction-runs-millis: 30000
    num-tests-per-eviction-run: 20